# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://github.com/codecov/example-node

language: "node_js"
node_js: # jest and eslint no longer support v4
  - "6"
  - "8"
install:
  - "npm install -g codecov"
  - "npm install"
os:
  - "linux"
  - "osx"
branches:
  only:
  - "master"
  - "develop"
  - "/^v\\d+\\.\\d+\\.\\d+(-.*)?$/"
cache:
  directories:
    - "node_modules"
script:
  - "npm run verify"
  - "codecov"
deploy:
  provider: "npm"
  on:
    tags: true
  email:
    secure: "xKVlxOJSnysk+OJ8XsA/GtUhyfU/LEHnnMulho2O55yp4GgrY3YQoZthtdUagS1wT+uIDqtsjmi0jjMruFTjMob0sQlsTDb6SjqAqXlNzcLxcorNP+afu/FbUtDKQHug8C1ZTcDNRuz8DILXPyDXjAXJZqrbz6pDXu9sHG0pvktPC1qGkwvV+PEueOcST1T5LHj2lEy7Mer24ER3KK9Ju52P632acON+XgoGtL0H9fN7CX1g0rE90X6Z+RZXJu70TnTI4fYSKUeCyxItOKF6NFfYvi9pfE1fKMPATPAMXPIoXNmbfzi4t0AxgsIZXyOdgB6FHgOEMzjQSFJQxoF6sbxQN7jzXb0DTfVyZGkA4EPUnr3zwxvQN542NKPf6QiWacQM8oYGeRDLF3WEN2hmH0Oa+13eV4Vjb2yLRXWqcQY6iYybI31oU+tugU32VkksbFzHNKnaybysbwKdQPn/CxYXXPSZUJ332XWM+woluoRn78FGpoJEArhnIRfvpj1FDhSjaRwINuCWfhRy6RsGwCKFoVuTze5cxuhS2RqK3NR/7Vz4xyfCXd/jTXhvcFAzGZ1YCqBEOs/Ah5Yh6Jr1jXvYLagSacs+FQ0OXdAigsHBUvDkcm3xS8NPCYof6mTeFSYmLoFuRE9fAuTYN3g3wUAjKFGqRtjYJUo5320VVqY="
  api_key:
    secure: "RVKIU9eOZKSsTIT5wjMXhCgNz6zlPBXDswlDCeTa5A0AQrb+NHntGjMPvqbyH2fygRgZal6oGNxeraMT94zDD2o7yM4riMDX1IsGk0pCgM4io2jB0wAXqoe8uN4gDirSNj1ENpuLEKuU5mY4m8x/rdcmSizbOe8SpVWiganvJRuCs+BT/qEHJdzi7ghLDYgFaXg4MTprseCvp38JDvNNH7kahxqvv3OfBO+GEnNGrb3/R0FfCBOw5F82UHdKOZC9jdDGVcSsWR4jtWNvLrl7qNe2+Wd+Fs1fwhZf7eVfjbKci+OSWTXh++mvzaigbznEk2x2c3CPYZWqfPsnBOVIAxK9IJrEBP3lJXf/YQipbIJgx8pEcyGAeM482VVz5Df13Qs8uTJEILMNjJJPAyHSOwCkmXXUmJZ8QCPVn1lXb4H2ta+6qNG/zBbxRl+1eITVUfPlarlVi6WzSMFDODOKWUQ6GthQdD+Q2RGpK8Qm6IvHSxE53yc6eVFuObqTzH84EQHX8fs1gflk1qUXeBSnT/AZSZOIPTVyHtv80/OQFWUo9q+sz/nkBx57deGJ/kblMstwJ3ZCY3BpZjrKn6AdbK8Vtp3/AX28BdcI6gvNO/9R+Uu0v7QZVAnhEoobn+ezsUZ15lXj6cCNu3scIkod3W+Ey8lZR7aJEyxctmhQXq4="
