# https://www.appveyor.com/docs/appveyor-yml
# https://www.appveyor.com/docs/lang/nodejs-iojs/

environment:
  matrix: # jest and eslint no longer support v4
  - nodejs_version: "6"
  - nodejs_version: "8"
  - nodejs_version: "10"
branches:
  only:
  - "master"
  - "develop"
cache:
- "node_modules"
install:
- ps: "Install-Product node $env:nodejs_version"
- "if exist node_modules npm prune"
- "if exist node_modules npm rebuild"
- "npm install"
test_script:
- "node --version"
- "npm --version"
- "npm run verify"
build: "off"
