# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on: push
name: Syntax check
jobs:
  syntax:
    name: Check CommonJS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-latest
        - macos-latest
        - ubuntu-latest
        nodejs:
        - "4.0.0"
        - "6.0.0"
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Output versions
      run: |
        node -v
        npm -v
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Install dependencies (only production)
      run: npm ci --only=production
    - name: Reinstall Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Output versions
      run: |
        node -v
        npm -v
    - name: Check syntax
      run: node ./dist/index.js
  syntax-mjs:
    name: Check ES Modules
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-latest
        - macos-latest
        - ubuntu-latest
        nodejs:
        - "8.5.0"
        - "10.0.0"
        exclude:
        - os: windows-latest # On Windows, v8.5.0 causes ERR_INVALID_PROTOCOL; https://github.com/nodejs/node/issues/15374
          nodejs: "8.5.0"
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Output versions
      run: |
        node -v
        npm -v
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Install dependencies (only production)
      run: npm ci --only=production
    - name: Reinstall Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Output versions
      run: |
        node -v
        npm -v
    - name: Check .mjs syntax
      run: node --experimental-modules ./dist/index.mjs
  syntax-mjs-windows:
    name: Check ES Modules on ${{ matrix.os }} / Node.js v${{ matrix.nodejs }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-latest
        nodejs:
        - "8.6.0"
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Output versions
      run: |
        node -v
        npm -v
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Install dependencies (only production)
      run: npm ci --only=production
    - name: Reinstall Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Output versions
      run: |
        node -v
        npm -v
    - name: Check .mjs syntax
      run: node --experimental-modules ./dist/index.mjs
  syntax-mjs-new:
    name: Check new ES Modules
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-latest
        - macos-latest
        - ubuntu-latest
        nodejs:
        - "12.0.0"
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Reinstall Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Output versions
      run: |
        node -v
        npm -v
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Install dependencies (only production)
      run: npm ci --only=production
    - name: Check .mjs syntax
      run: node --experimental-modules --es-module-specifier-resolution=node ./dist/index.mjs
