# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  push:
    branches:
    - master
    - develop
    - "v*"
  pull_request:
name: Syntax check
jobs:
  syntax:
    name: Check CommonJS
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
        - "Windows-latest"
        - "macOS-latest"
        - "Ubuntu-latest"
        nodejs:
        - "4.0.0"
        - "6.0.0"
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install npm packages
      run: npm i -g node-gyp
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Install dependencies (only production)
      run: npm ci --only=production
    - name: Reinstall Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Confirm Node.js version
      run: node -v
    - name: Check syntax
      run: node ./dist/index.js
  syntax-mjs:
    name: Check ES Modules
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
        - "Windows-latest"
        - "macOS-latest"
        - "Ubuntu-latest"
        nodejs:
        - "8.5.0"
        - "10.0.0"
        exclude:
        - platform: "Windows-latest" # In Windows, v8.5.0 causes ERR_INVALID_PROTOCOL; https://github.com/nodejs/node/issues/15374
          nodejs: "8.5.0"
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install npm packages
      run: npm i -g node-gyp
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Install dependencies (only production)
      run: npm ci --only=production
    - name: Reinstall Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Confirm Node.js version
      run: node -v
    - name: Check .mjs syntax
      run: node --experimental-modules ./dist/index.mjs
  syntax-mjs-windows:
    name: Check ES Modules on ${{ matrix.platform }} / Node.js v${{ matrix.nodejs }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
        - "Windows-latest"
        nodejs:
        - "8.6.0"
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Install Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install npm packages
      run: npm i -g node-gyp
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Install dependencies (only production)
      run: npm ci --only=production
    - name: Reinstall Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Confirm Node.js version
      run: node -v
    - name: Check .mjs syntax
      run: node --experimental-modules ./dist/index.mjs
  syntax-mjs-new:
    name: Check new ES Modules
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
        - "Windows-latest"
        - "macOS-latest"
        - "Ubuntu-latest"
        nodejs:
        - "12.0.0"
      fail-fast: false
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Reinstall Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Install npm packages
      run: npm i -g node-gyp
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Install dependencies (only production)
      run: npm ci --only=production
    - name: Check .mjs syntax
      run: node --experimental-modules --es-module-specifier-resolution=node ./dist/index.mjs
